### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ndvbd** [raymondhs/lang-8-process#1]
Can you provide a few examples on how to run the scripts?

For example, when I run 
`python3 preprocess_lang8.py -d entries.train -o output -k keep`
I get

```
Traceback (most recent call last):
  File "preprocess_lang8.py", line 96, in <module>
    process_func, fin.readlines(), args.jobs
  File "preprocess_lang8.py", line 40, in process
    row = json.loads(re.sub(r'[\x00-\x1F]+', '', line))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)
```

**Comment by raymondhs** [comment]
Hi, you can check `clean_corpus.sh` for a running example. The Python script `preprocess_lang8.py` is used to preprocess the raw json file from Lang-8 `lang-8-20111007-L1-v2.dat`.
